version: '3.8'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kibana
    restart: always
    env_file:
      ./.env
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./certs:/usr/share/kibana/config/certs
    ports:
      - 5601:5601
    extra_hosts:
      - "elasticsearch:${ELASTICSEARCH}"
