version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: elasticsearch
    restart: always
    environment:
      - node.name=es-node-1
      - cluster.name=docker-cluster
      - network.host=0.0.0.0
      - network.publish_host=es-node-1
      - xpack.security.enabled=false
     - xpack.monitoring.collection.enabled=true
#      - "ES_JAVA_OPTS=-Xms16g -Xmx16g"
    volumes:
      - type: bind
        source: /home/data
        target: /usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      elk-network:

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kibana
    restart: always
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      SERVER_NAME: es-node-1_kibana
#      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      elk-network:

networks:
  elk-network:
